#!/usr/bin/env python
import glob, os

fileNames  = glob.glob("initial_files/*.py")
fileNames += glob.glob("initial_files/*.hexImage")

for fn in fileNames:
    print "Burning "+ fn
    print os.popen("ampy -p /dev/ttyUSB0 put "+ fn).read()
