#!/usr/bin/env python3
import glob, os

fileNames  = glob.glob("initial_files/*.py")
fileNames += glob.glob("initial_files/*.hexImage")

for fn in fileNames:
    print("Burning "+ fn)
    cmd = "ampy -p /dev/ttyUSB0 put "+ fn
    print(os.popen(cmd).read())
